In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Social_Network_Ads.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
np.set_printoptions(precision=6) # Printa apenas 6 casas decimais para arrays

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print('X_train antes de padronizar')
print(X_train[:10]) # Pegando as 10 primeiras linhas
print('*********************************')
print('X_test antes de padronizar')
print(X_test[:10])

X_train antes de padronizar
[[    58 144000]
 [    59  83000]
 [    24  55000]
 [    26  35000]
 [    58  38000]
 [    42  80000]
 [    40  75000]
 [    59 130000]
 [    46  41000]
 [    41  60000]]
*********************************
X_test antes de padronizar
[[    30  87000]
 [    38  50000]
 [    35  75000]
 [    30  79000]
 [    35  50000]
 [    27  20000]
 [    31  15000]
 [    36 144000]
 [    18  68000]
 [    47  43000]]


In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) # Como é considerado dado novo apenas transform, evita fazamento de dados
print('X_train depois de padronizar')
print(X_train[:10])
print('*********************************')
print('X_test depois de padronizar')
print(X_test[:10])

X_train depois de padronizar
[[ 1.92295   2.146016]
 [ 2.020161  0.378719]
 [-1.382215 -0.432499]
 [-1.187794 -1.01194 ]
 [ 1.92295  -0.925024]
 [ 0.367578  0.291803]
 [ 0.173157  0.146943]
 [ 2.020161  1.740407]
 [ 0.756421 -0.838108]
 [ 0.270367 -0.287638]]
*********************************
X_test depois de padronizar
[[-0.798951  0.494608]
 [-0.021265 -0.577359]
 [-0.312897  0.146943]
 [-0.798951  0.262831]
 [-0.312897 -0.577359]
 [-1.090583 -1.446521]
 [-0.70174  -1.591382]
 [-0.215686  2.146016]
 [-1.96548  -0.055862]
 [ 0.853632 -0.780164]]
